<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace lliyplliuk\eBaySDK\Merchandising\Services;

class MerchandisingService extends \lliyplliuk\eBaySDK\Merchandising\Services\MerchandisingBaseService
{
    const API_VERSION = '1.5.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest $request
     * @return \lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse
     */
    public function getRelatedCategoryItems(\lliyplliuk\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest $request)
    {
        return $this->getRelatedCategoryItemsAsync($request)->wait();
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRelatedCategoryItemsAsync(\lliyplliuk\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getRelatedCategoryItems',
            $request,
            '\lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest $request
     * @return \lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse
     */
    public function getMostWatchedItems(\lliyplliuk\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest $request)
    {
        return $this->getMostWatchedItemsAsync($request)->wait();
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMostWatchedItemsAsync(\lliyplliuk\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getMostWatchedItems',
            $request,
            '\lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest $request
     * @return \lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceProductResponse
     */
    public function getTopSellingProducts(\lliyplliuk\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest $request)
    {
        return $this->getTopSellingProductsAsync($request)->wait();
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTopSellingProductsAsync(\lliyplliuk\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest $request)
    {
        return $this->callOperationAsync(
            'getTopSellingProducts',
            $request,
            '\lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceProductResponse'
        );
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetDealsRequest $request
     * @return \lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse
     */
    public function getDeals(\lliyplliuk\eBaySDK\Merchandising\Types\GetDealsRequest $request)
    {
        return $this->getDealsAsync($request)->wait();
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetDealsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDealsAsync(\lliyplliuk\eBaySDK\Merchandising\Types\GetDealsRequest $request)
    {
        return $this->callOperationAsync(
            'getDeals',
            $request,
            '\lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetSimilarItemsRequest $request
     * @return \lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse
     */
    public function getSimilarItems(\lliyplliuk\eBaySDK\Merchandising\Types\GetSimilarItemsRequest $request)
    {
        return $this->getSimilarItemsAsync($request)->wait();
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetSimilarItemsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSimilarItemsAsync(\lliyplliuk\eBaySDK\Merchandising\Types\GetSimilarItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getSimilarItems',
            $request,
            '\lliyplliuk\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetVersionRequest $request
     * @return \lliyplliuk\eBaySDK\Merchandising\Types\GetVersionResponse
     */
    public function getVersion(\lliyplliuk\eBaySDK\Merchandising\Types\GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param \lliyplliuk\eBaySDK\Merchandising\Types\GetVersionRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getVersionAsync(\lliyplliuk\eBaySDK\Merchandising\Types\GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\lliyplliuk\eBaySDK\Merchandising\Types\GetVersionResponse'
        );
    }
}
