<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace lliyplliuk\eBaySDK\Test\BulkDataExchange\Types;

use lliyplliuk\eBaySDK\BulkDataExchange\Types\StartUploadJobRequest;

class StartUploadJobRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new StartUploadJobRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\BulkDataExchange\Types\StartUploadJobRequest', $this->obj);
    }

    public function testExtendsBaseServiceRequest()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\BulkDataExchange\Types\BaseServiceRequest', $this->obj);
    }
}
