<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace lliyplliuk\eBaySDK\Test\Shopping\Enums;

use lliyplliuk\eBaySDK\Shopping\Enums\FeedbackRatingDetailCodeType;

class FeedbackRatingDetailCodeTypeTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new FeedbackRatingDetailCodeType();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\Shopping\Enums\FeedbackRatingDetailCodeType', $this->obj);
    }
}
