<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace lliyplliuk\eBaySDK\Test\PostOrder\Enums;

use lliyplliuk\eBaySDK\PostOrder\Enums\InquirySearchFieldGroupEnum;

class InquirySearchFieldGroupEnumTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new InquirySearchFieldGroupEnum();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\PostOrder\Enums\InquirySearchFieldGroupEnum', $this->obj);
    }
}
