<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace lliyplliuk\eBaySDK\Test\Taxonomy\Types;

use lliyplliuk\eBaySDK\Taxonomy\Types\GetADefaultCategoryTreeIdRestResponse;

class GetADefaultCategoryTreeIdRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetADefaultCategoryTreeIdRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\Taxonomy\Types\GetADefaultCategoryTreeIdRestResponse', $this->obj);
    }

    public function testExtendsBaseCategoryTree()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\Taxonomy\Types\BaseCategoryTree', $this->obj);
    }
}
