<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace lliyplliuk\eBaySDK\Test\Metadata\Types;

use lliyplliuk\eBaySDK\Metadata\Types\GetPoliciesForAutoPartsCompatibilityRestResponse;

class GetPoliciesForAutoPartsCompatibilityRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetPoliciesForAutoPartsCompatibilityRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\Metadata\Types\GetPoliciesForAutoPartsCompatibilityRestResponse', $this->obj);
    }

    public function testExtendsAutomotivePartsCompatibilityPolicyResponse()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\Metadata\Types\AutomotivePartsCompatibilityPolicyResponse', $this->obj);
    }
}
