<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace lliyplliuk\eBaySDK\Test\RelatedItemsManagement\Enums;

use lliyplliuk\eBaySDK\RelatedItemsManagement\Enums\DiscountTypeEnum;

class DiscountTypeEnumTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new DiscountTypeEnum();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\RelatedItemsManagement\Enums\DiscountTypeEnum', $this->obj);
    }
}
