<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace lliyplliuk\eBaySDK\Test\MerchantData\Enums;

use lliyplliuk\eBaySDK\MerchantData\Enums\ItemSpecificSourceCodeType;

class ItemSpecificSourceCodeTypeTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new ItemSpecificSourceCodeType();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\lliyplliuk\eBaySDK\MerchantData\Enums\ItemSpecificSourceCodeType', $this->obj);
    }
}
